domain: brpl20.github.io
url: https://brpl20.github.io

title: Pellizzetti Blog
email: your-email@example.com
description: Adicionando uma descrição para exibir na página home.

markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
