domain: brpl20.github.io
url: https://brpl20.github.io

title: Pellizzetti Blog
email: your-email@example.com
description: Adicionando uma descrição para exibir na página home.

markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
